#!/usr/bin/env php
<?php

$args = $argv;
array_shift($args);

if (!array_filter($args, function ($a) { return strpos($a, '-') === 0; } )) {
    $args[] = '-C';
}

$indent = '    ';

// execute `tree`
exec('tree ' . implode(' ', $args), $output);

$currentPos = null;
$indentLv = 0;
foreach ($output as $line) {
    if ($line === '') {
        echo PHP_EOL;
        continue;
    }

    $pos = null;
    foreach (['│', '├', '└'] as $needle) {
        $p = mb_strrpos($line, $needle);
        if ($p !== false) {
            $pos = (int) max($p, $pos);
        }
    }
    if ($pos === null) {
        $indentLv = 0;
    } elseif ($pos === 0) {
        $indentLv = 1;
    } elseif ($currentPos < $pos) {
        $indentLv++;
    } elseif ($currentPos > $pos) {
        $indentLv--;
    }
    $currentPos = $pos;

    $name = '(unknown)';
    if (preg_match('/── (.+)$/', $line, $matches)) {
        $name = $matches[1];
    } else {
        $name = $line;
    }

    echo str_repeat($indent, $indentLv), '* ', $name, PHP_EOL;
}
